%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\mdorf75\Projects\RPiSensor_Nash\TSens\Data\tsensdata.csv
%
% Auto-generated by MATLAB on 22-May-2020 16:27:00

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "AccX", "AccY", "AccZ", "GyrX", "GyrY", "GyrZ", "Rolldeg", "Pitchdeg", "Yawdeg", "Heading", "X", "Y", "Z", "Vx", "Vy", "Vz", "AccXraw", "AccYraw", ...
    "AccZraw","RollAcc","PitchAcc","Latitude", "Longitude", "GPShspeed", "GPSalt","MagX","MagY","MagZ"];
opts.VariableTypes = ["double", "double", "double", "double","double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double","double","double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
[file,path] = uigetfile({'*.csv';'*.m';'*.slx';'*.mat';'*.*'},...
                          'File Selector')
%data = readtable("D:\mdorf75\Projects\RPiSensor_Nash\TSens\Data\T25-05-2020_20-49-18.csv", opts);
data = readtable(strcat(path,'\',file), opts);
data.DateNum=data.Time+datetime;

%% Clear temporary variables
clear opts
%% Cut off
%id = find(data.Time >100);
%data = data(id,:);
%%
figure;
ap(1)=subplot(2,1,1),
    plot(data.Time,data.Rolldeg,'b','LineWidth',2);
    hold on;    
    plot(data.Time,data.RollAcc,'g','LineWidth',1);
    %plot(data.Time,(data.Roll_accdeg),'+','Color',[0.3 0 0.8]);
    %plot(data.Time,(data.Roll_gyrdeg),'*','Color',[0.75 0 1]);
    %datetick('x')
    ylabel('Roll deg');
    xlabel('Time (s)');
    legend('Fusion Kalman','Accel only');
    grid minor;
ap(2)=subplot(2,1,2),
    plot(data.Time,data.Pitchdeg,'r','LineWidth',2);
    hold on;   
    plot(data.Time,data.PitchAcc,'g','LineWidth',1);
	%plot(data.Time,(data.Pitch_accdeg),'+','Color',[0.8 0 0.3]);
    %plot(data.Time,(data.Pitch_gyrdeg),'*','Color',[1.0 0 0.75]);
    %datetick('x')
    ylabel('Pitch deg');
    xlabel('Time (s)');
    %legend('Fusion','Accel only','Gyro only');
    legend('Fusion Kalman','Accel only');
    grid minor;
%ap(3)=subplot(3,1,3),
    %plot(data.Time,data.Yawdeg,'g','LineWidth',2);
%    hold on;    
    %plot(data.Time,(data.Yaw_accdeg),'+','Color',[0. 0.8 0.3]);
    %plot(data.Time,(data.Yaw_gyrdeg),'+','Color',[0. 1.0 0.75]);
%    %datetick('x')
%    ylabel('Yaw deg');
%    legend('Fusion','Accel only','Gyro only');
%    grid minor;
linkaxes(ap,'x');axis tight
%%
figure;
ax(1)=subplot(3,2,1),
    plot(data.Time,data.AccX,'LineWidth',2);
    hold on;    
    plot(data.Time,data.AccXraw,'LineWidth',1);
    %datetick('x')
    ylabel('Accleration X-Dir m/s^2');
    xlabel('Time (s)');
    xlabel('Time (s)');
    legend('Filtered Acceleration','Raw Acceleration')
    grid minor;
    %ylim([-0.01 0.01])
ax(2)=subplot(3,2,3),    
    plot(data.Time,data.AccY,'r','LineWidth',2);
    hold on;
     plot(data.Time,data.AccYraw,'LineWidth',1);
    %datetick('x')
    ylabel('Accleration Y-Dir m/s^2');
    xlabel('Time (s)');
    grid minor;
    legend('Filtered Acceleration','Raw Acceleration')
    %ylim([-0.01 0.01])
ax(3)=subplot(3,2,5),       
    plot(data.Time,data.AccZ,'g','LineWidth',2);    
    hold on;   
     plot(data.Time,data.AccZraw,'LineWidth',1);
    %datetick('x')
    ylabel('Accleration Z-Dir m/s^2');
    legend('Filtered Acceleration','Raw Acceleration')
    xlabel('Time (s)');
    ylim([8. 12])
    grid minor;
linkaxes(ax,'x');%axis tight
%
ax(1)=subplot(3,2,2),
    plot(data.Time,data.GyrX,'LineWidth',2);
    hold on;    
    %datetick('x')
    ylabel('Gyr X rad/s');
    xlabel('Time (s)');
    grid minor;
    %ylim([-0.1 0.1])
ax(2)=subplot(3,2,4),    
    plot(data.Time,data.GyrY,'r','LineWidth',2);
    hold on;
    %datetick('x')
    ylabel('Gyr Y rad/s');
    xlabel('Time (s)');
    grid minor;
    %ylim([-0.1 0.1])
ax(3)=subplot(3,2,6),       
    plot(data.Time,data.GyrZ,'g','LineWidth',2);    
    hold on;
    %datetick('x')
    ylabel('Gyr Z rad/s');
    xlabel('Time (s)');
    grid minor;
    %ylim([9.7 10.])
linkaxes(ax,'x');axis tight
%%
figure;
    plot(data.Time, wrapTo360(data.Heading),'g','LineWidth',2);    
    hold on;
    plot(data.Time, wrapTo180(data.Yawdeg),'r','LineWidth',2);    
    %datetick('x')
    ylabel('Heading deg');
    xlabel('Time (s)');
    grid minor;
    axis tight
    legend('Raw Compass Heading','Yaw from Kalman');
	ylim([0 360])
%%
figure;
ax(1)=subplot(3,1,1),
    yyaxis left
    plot(data.Time,data.X);
    ylabel('Displacement X-Dir (m)');
    hold on;
    yyaxis right
    plot(data.Time,data.Vx);
    ylabel('Velocity X-Dir (m/s)');
    %plot(data.Time,data.AccX,'LineWidth',1);    
    xlabel('Time (s)');
    grid minor;    
ax(2)=subplot(3,1,2),    
    yyaxis left
    plot(data.Time,data.Y);
    ylabel('Displacement  Y-Dir (m)');
    hold on;
    yyaxis right
    plot(data.Time,data.Vy);
    ylabel('Velocity Y-Dir (m/s)');
    %plot(data.Time,data.AccY,'LineWidth',1);
    xlabel('Time (s)');
    grid minor;    
ax(3)=subplot(3,1,3),    
    yyaxis left
    plot(data.Time,data.Z);
    ylabel('Displacement Z-Dir (m)');
    hold on;
    yyaxis right
    plot(data.Time,data.Vz);    
    ylabel('Velocity Z-Dir (m/s)');
    %plot(data.Time,data.AccZ,'LineWidth',1);    
    xlabel('Time (s)');
    grid minor;    
%%
figure;
ax(1)=subplot(3,1,1),
    yyaxis left
    plot(data.Time,data.Vx);
    ylabel('X-Dir Velocity m/s');
    hold on;
    yyaxis right    
    plot(data.Time,data.AccX,'LineWidth',1);
    ylabel('X-Dir Acceleration (m/^2)');
    xlabel('Time (s)');
    grid minor;    
ax(2)=subplot(3,1,2),    
    yyaxis left
    plot(data.Time,data.Vy);
    ylabel('Y-Dir Velocity m/s');
    hold on;
    yyaxis right
    plot(data.Time,data.AccY,'LineWidth',1);
    ylabel('Y-Dir Acceleration (m/^2)');
    xlabel('Time (s)');
    grid minor;    
ax(3)=subplot(3,1,3),    
    yyaxis left
    plot(data.Time,data.Vz);    
    ylabel('Z-Dir Velocity m/s');
    hold on;
    yyaxis right    
    plot(data.Time,data.AccZ,'LineWidth',1);
    ylabel('Z-Dir Acceleration (m/^2)');
    xlabel('Time (s)');
    grid minor;    
%%
figure;
plot(data.Time, data.MagX,'r','LineWidth',2)
hold on
plot(data.Time, data.MagY,'g','LineWidth',2)
plot(data.Time, data.MagZ,'b','LineWidth',2)
grid minor;
xlabel('Time (s)');
ylabel(' Magnetometer uT')
legend('MagX','MagY','MagZ')
%% Callibration
id = find(data.Time>750 & data.Time<830)
0.2458-rad2deg(mean(data.GyrX(id))) %    'gyroXoffset' : 
4.4413-rad2deg(mean(data.GyrY(id))) %    'gyroYoffset' :
1.8421-rad2deg(mean(data.GyrZ(id))) %    'gyroZoffset' :
0.0164-mean(data.AccX)/9.81 %    'accXoffset'
-0.0312-mean(data.AccY)/9.81 %   'accYoffset'
-0.0009-mean(9.81-data.AccZ)/9.81 %  'accZoffset'
%
disp('ddd')
rad2deg(mean(data.GyrX(id))) %    'gyroXoffset' : 
rad2deg(mean(data.GyrY(id))) %    'gyroYoffset' :
rad2deg(mean(data.GyrZ(id))) %    'gyroZoffset' :
mean(data.AccX)/9.81 %    'accXoffset'
mean(data.AccY)/9.81 %   'accYoffset'
mean(9.81-data.AccZ)/9.81 %  'accZoffset'


     